# Main menu navigation
# ---------------
# format: xxx: 連結 || icon
# sub-menu
# xxx || icon:
#   xxx || 連結 || icon
menu:
  Home: / || fa fa-home
  Archives: /archives/ || fa fa-archive
  Tags: /tags/ || fa fa-tags
  Categories: /categories/ || fa fa-folder-open
  Link: /link/ || fa fa-link
  About: /about/ || fa fa-heart
  List||fa fa-list:
    - Music || /music/ || fa fa-music
    - Movie || /movies/ || fa fa-film

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
# pwa:
#   enable: true
#   manifest: /img/pwa/manifest.json
#   theme_color: "#fff"
#   apple_touch_icon: /img/pwa/apple-touch-icon.png
#   favicon_32_32: /img/pwa/32.png
#   favicon_16_16: /img/pwa/16.png
#   mask_icon: /img/pwa/safari-pinned-tab.svg

# Highlight theme
# ---------------
highlight_theme: light # default / darker / pale night / light / ocean
highlight_copy: true #代碼複製按鈕
highlight_lang: true #代碼語言顯示
highlight_shrink: false # true 全部代碼框不展開，需點擊 '>' 打開 / false 代碼框展開，有'>'點擊按鈕 | none 代碼框展開，不顯示 '>' 按鈕

code_word_wrap: false

# copy setting
# 是否禁止複製（如果禁止，highlight_copy的功能將無效)
# copyright 複製的內容後面加上版權信息
copy:
  enable: true # true 開啟 / false 禁止
  copyright: false

# social settings
# formal:
#   icon: link || the description
# ---------------
social:
  fa fa-github: https://github.com/jerryc127 || Github
  fa fa-envelope: mailto:xxxxxxx@gmail.com || Email
  fa fa-rss: /atom.xml || RSS

####    search    ####
# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 6

  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result
    hits_stats: '${hits} results found in ${time} ms'

# Local search
# Please see doc for more details: https://docs.jerryc.me/config.html#本地搜索
# ---------------
local_search:
  enable: false
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result

# MathJax
# Please see doc for more details: https://docs.jerryc.me/config.html#mathjax
# ---------------
mathjax:
  enable: false
  # true 表示每一頁都加載mathjax.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 mathjax: true
  per_page: false

# KaTeX
# ---------------
katex:
  enable: false
  # true 表示每一頁都加載katex.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 katex: true
  per_page: false
  hide_scrollbar: true

# mermaid
# see https://github.com/knsv/mermaid
# -------------------------------
mermaid:
  enable: false
  # built-in themes: default/forest/dark/neutral
  theme: default

# Favicon
# ---------------
favicon: /img/favicon.png

# Post info settings
# ---------------
avatar:
  img: /img/avatar.png
  effect: false # 頭像會一直轉圈

# the banner image of index
index_img:

# if the banner of page not setting,it will show the top_img
default_top_img: https://i.loli.net/2020/05/01/IuWi8QbHvzjlOPw.jpg

# the banner image of archive page
archive_img:

# the banner image of tag page
# tag page, look like https://xxxxxxxxx.com/tags/butterfly
tag_img:

# the banner image of category page
# category page, look like https://xxxxxxxxx.com/categories/butterfly
category_img:

# 如果你有使用hexo-douban，可配置這個
# douban:
#   meta: false
#   movies_img:
#   books_img:
#   games_img:

cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover:
    - https://i.loli.net/2020/05/01/gkihqEjXxJ5UZ1C.jpg

# if the photo link cannot connect,it will show that
lodding_bg:
  flink: /img/friend_404.gif #404後圖片
  post_page: /img/404.jpg #404後圖片
#  post: /img/loading.gif ##加載動畫

# A simple 404 page
error_404:
  enable: false
  subtitle: 'Page Not Found'
  background:

post_meta:
  page:
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    categories: true # true or false 主頁是否顯示分類
    tags: false # true or false 主頁是否顯示標籤
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤

# Please see doc for more details: https://docs.jerryc.me/config.html#字數統計
wordcount:
  enable: false
  post_wordcount: true
  min2read: true
  total_wordcount: true

toc:
  enable: true
  number: true

# auto open the sidebar in 'post'
auto_open_sidebar:
  enable: true

post_copyright:
  enable: true
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 自動節選
auto_excerpt:
  enable: true
  length: 150

####    Share System    ####
# -----------------------------------------
addThis:
  enable: false
  pubid:

sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq

# https://www.addtoany.com/
addtoany:
  enable: false
  item:
    - facebook
    - twitter
    - wechat
    - sina_weibo
    - facebook_messenger
    - email
    - copy_link

####   Comments System    ####
# ------------------------------------
disqus:
  enable: false
  shortname:
  count: false # dispaly comment count in top_img

# Disqus.js版評論系統，應對大陸長城的折中方案，兼容原版：https://github.com/SukkaW/DisqusJS
# API 申請地址：https://disqus.com/api/applications/
# 與 disqus 共用樣式
disqusjs:
  enable: false
  shortname:
  siteName:
  apikey:
  api: https://disqus.skk.moe/disqus/ #一般情況下無需修改 API 地址
  admin:
  adminLabel:
  count: false # dispaly comment count in top_img

laibili:
  enable: false
  uid:

gitalk:
  enable: false
  client_id:
  client_secret:
  repo:
  owner:
  admin:
  language: zh-CN # en , zh-CN , zh-TW
  perPage: 10 # Pagination size, with maximum 100.
  distractionFreeMode: false # Facebook-like distraction free mode.
  pagerDirection: last # Comment sorting direction, available values are last and first.
  createIssueManually: false # Gitalk will create a corresponding github issue for your every single page automatically
  count: false # dispaly comment count in top_img

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  appId: # leancloud application app id
  appKey: # leancloud application app key
  notify: false # valine mail notify (true/false) Deprecated in v1.4.0+
  verify: false # valine verify code (true/false) Deprecated in v1.4.0+
  pageSize: 10 # comment list page size
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  lang: en # i18n: zh-CN/zh-TW/en/ja
  placeholder: Please leave your footprints # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
  recordIP: false # Record reviewer IP
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  emojiCDN: # emoji CDN
  enableQQ: false # enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  requiredFields: nick,mail # required fields nick/mail/link
  bg: # valine background
  count: false # dispaly comment count in top_img

# utterances
# https://utteranc.es/
utterances:
  enable: false
  repo:
  # 可選 pathname/url/title/og:title
  issue_term: pathname
  # 可選 github-light/github-dark/github-dark-orange/icy-dark/dark-blue/photon-dark
  light_theme: github-light
  dark_theme: photon-dark

# Facebook Comments Plugin
# https://developers.facebook.com/docs/plugins/comments/
facebook_comments:
  enable: false
  app_id:
  user_id: # optional
  pageSize: 10 # The number of comments to show
  order_by: social # social/time/reverse_time
  lang: en_US # Language en_US/zh_CN/zh_TW and so on
  count: false

#####     Footer Settings    ####
# ------------------------------------
since: 2020

footer_custom_text:

footer_copyright:
  enable: true

ICP:
  enable: false
  url:
  text:
  icon: /img/icp.png

####   Analysis    ####
# ---------------
baidu_analytics:

# Google Analytics
google_analytics:

# Tencent_analytics ID
tencent_analytics:

# Ads
# ---------------
# Google Adsense
google_adsense:
  enable: false
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client:
  enable_page_level_ads: true

# 廣告插入位置
# 適用於開啓手動廣告的配置
# ad:
#   index:
#   aside:
#   post:

####    站長驗證    ####
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:

# Bing Webmaster tools verification setting
# See: https://www.bing.com/webmaster/
bing_site_verification:

# Baidu Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification:

# 360 Webmaster tools verification setting
# see http://zhanzhang.so.com/
qihu_site_verification:

# 打賞按鈕
reward:
  enable: true
  QR_code:
    - itemlist:
        img: /img/wechat.jpg
        text: 微信
    - itemlist:
        img: /img/alipay.jpg
        text: 支付寶

# 推薦文章
related_post:
  enable: true
  limit: 6 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日

# figcaption
# 圖片描述文字
photofigcaption: false

# anchor
# when you scroll in post, the url will update according to header id.
anchor: false

####    美化/效果    ####
#--------------------------------

# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
# theme_color:
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00c4b6"
#   button_hover: "#FF7242"
#   text_selection: "#00c4b6"
#   link_color: "#99a9bf"
#   meta_color: "#858585"
#   hr_color: "#A4D8FA"
#   code_foreground: "#F47466"
#   code_background: "rgba(27, 31, 35, .05)"
#   toc_color: "#00c4b6"
#   blockquote_padding_color: "#49b1f5"
#   blockquote_background_color: "#49b1f5"

# 主頁設置
# 默認top_img全屏，site_info在中間
# 使用默認, 都無需填寫（建議默認）
index_site_info_top: # 主頁標題距離頂部距離  例如 300px/300em/300rem/10%
index_top_img_height: # 主頁top_img高度 例如 300px/300em/300rem  不能使用百分比

# category和tag頁的UI設置
# index 值代表 UI將與首頁的UI一樣
# 默認跟archives頁面UI一樣
category_ui: # 留空或index
tag_ui: # 留空或index

# 設置網站背景
# 可設置圖片 或者 顔色
# 圖片格式 background: url(http://xxxxxx.com/xxx.jpg)
# 顔色 background: '#49B202'
# 留空 顯示白色
background:

# footer是否顯示圖片背景(與top_img一致)
footer_bg: false

# 背景特效
# 避免卡頓，建議只開啟一個
# canvas_ribbon 禁止彩帶背景
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false # false 手機端不顯示 true 手機端顯示

# 動態彩帶
canvas_ribbon_piao:
  enable: false
  mobile: false # false 手機端不顯示 true 手機端顯示

# canvas_nest
# https://github.com/hustcc/canvas-nest.js
canvas_nest:
  enable: false
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false # false 手機端不顯示 true 手機端顯示

# 打字效果
activate_power_mode:
  enable: false
  colorful: true # 冒光特效
  shake: true # 抖動特效

# 鼠標點擊效果
# 避免卡頓，建議只開啟一個
# 點擊煙火特效
fireworks:
  enable: false

# 點擊出現愛心
click_heart:
  enable: false

# 點擊出現文字，文字可自行修改
ClickShowText:
  enable: false
  text:
    - I
    - LOVE
    - YOU
  fontSize: 15px

# 網站顯示模式
# light 默認模式
# dark 黑暗模式（不建議）
display_mode: light

# 美化頁面顯示
beautify:
  enable: false
  field: post # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: '#F47466'

# 全局字體
font:
  enable: false
  font-family: Lato, Helvetica Neue For Number, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, PingFang SC, Hiragino Sans GB, MicrMicrosoft YaHei", Helvetica Neue, Helvetica, Arial, sans-serif
  code-font: consolas, Menlo, "PingFang SC", "Microsoft YaHei", monospace, Helvetica Neue For Number

# 網站名字字體
# 左上角網站名字 主頁居中網站名字
blog_title_font:
  font_link: https://fonts.googleapis.com/css?family=Titillium+Web #字體鏈接
  font-family: Titillium Web, PingFang SC, Hiragino Sans GB, "Microsoft YaHei", Helvetica Neue, Helvetica, Arial, sans-serif

# 水平分隔綫
hr:
  enable: false
  icon: '\f21c' #fontawesome上圖標的Unicode
  icon-top: -20px

# 主頁subtitle
subtitle:
  enable: true
  # 打字效果
  effect: true
  # 循環或者只打字一次
  loop: false
  # source調用第三方服務
  # source: false 關閉調用
  # source: 1  調用搏天api的隨機語錄（簡體） https://api.btstu.cn/
  # source: 2  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 3  調用一句網（簡體） http://yijuzhan.com/
  # source: 4  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: false
  # (如果有英文逗號' , '，請使用轉義字符 &#44;)
  # 如果關閉打字效果，subtitle只會顯示sub的第一行文字
  sub:
    - 今日事&#44;今日畢
    - Never put off till tomorrow what you can do today

# fontawesome圖標
# 默認使用的是 fontawesome v4版本的圖標
fontawesome_v5:
  enable: false

# 加載動畫 Loading Animation
preloader: false

####    側邊欄    ####
#-------------------------------------
# 側邊欄顯示設置
aside:
  enable: true
  mobile: true # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: right # left or right
  card_author:
    enable: true
    description:
  card_announcement:
    enable: true
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo: true

# busuanzi count for PV / UV in site
# 訪問人數
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 網頁開通時間
# 格式: 月/日/年 時間
# 也可以寫成 年/月/日 時間
runtimeshow:
  enable: true
  start_date: 6/7/2018 00:00:00

####   右下角按鈕  ####
#----------------------------------------------
# 簡繁轉換
translate:
  enable: true
  # 默認按鈕顯示文字
  default: 繁
  #網站默認語言，1: 繁體中文, 2: 簡體中文
  defaultEncoding: 2
  #延遲時間,若不在前, 要設定延遲翻譯時間, 如100表示100ms,默認為0
  translateDelay: 0
  #博客網址
  cookieDomain: 'https://xxx/'
  #當文字是簡體時，按鈕顯示的文字
  msgToTraditionalChinese: '繁'
  #當文字是繁體時，按鈕顯示的文字
  msgToSimplifiedChinese: '簡'

#閲讀模式
readmode:
  enable: true

# dark mode
darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  # 自動切換 dark mode和 light mode
  # autoChangeMode: 1  跟隨系統而變化，不支持的瀏覽器/系統將按照時間晚上6點到早上6點之間切換為 dark mode
  # autoChangeMode: 2  只按照時間晚上6點到早上6點之間切換為 dark mode
  # autoChangeMode: false 取消自動切換
  autoChangeMode: 1

####    other     ####
#------------------------------------------------

# 圖片大圖查看模式
# 可選 medium_zoom 或者 fancybox
# 只選一個 或者 兩個都不選
#--------------------------------------------
# medium_zoom https://github.com/francoischalifour/medium-zoom
medium_zoom:
  enable: false

# fancybox http://fancyapps.com/fancybox/3/
fancybox:
  enable: true

# Snackbar 彈窗
# https://github.com/polonel/SnackBar
# position 彈窗位置
# 可選 top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: false
  position: bottom-left
  bg_light: '#49b1f5' #light mode時彈窗背景
  bg_dark: '#2d3035' #dark mode時彈窗背景

#百度推送
baidu_push:
  enable: false

# https://instant.page/
# prefetch預加載
instantpage:
  enable: true

# https://github.com/vinta/pangu.js
# 中英文之間添加空格
pangu:
  enable: false
  field: page # page/post

# Note (Bootstrap Callout)
# https://muse.theme-next.org/docs/tag-plugins/note
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# 圖片懶加載
# https://github.com/ApoorvSaxena/lozad.js
lazyload: false

# 避免重複網址分散seo
canonical: true

# 禁止百度轉碼
disable_baidu_transformation: true

# twitter分享自動帶上樣式
# https://i.loli.net/2019/09/08/qm3RfvUCKbct1Wz.png
twitter_meta: true

# facebook QQ 等 分享自動帶上樣式
# https://i.loli.net/2019/09/08/2wbFJEKloisRvhj.png
Open_Graph_meta: true

# 開啟hexo自帶的緩存，加快生成速度
fragment_cache: true

# inject
# 插入代码到头部</head>之前 和 尾部</body>之前
inject:
  head:
  # - <link rel="stylesheet" href="xxxxx">
  bottom:
    # - <script src="xxxx"></script>

# CDN
# 非必要不要修改
CDN:
  # main
  main_css: /css/index.css
  jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
  main: /js/main.js
  utils: /js/utils.js

  # comments
  blueimp_md5: https://cdn.jsdelivr.net/npm/blueimp-md5/js/md5.min.js
  gitalk: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  gitalk_css: https://cdn.jsdelivr.net/npm/gitalk/dist/gitalk.min.css
  valine: https://cdn.jsdelivr.net/npm/valine/dist/Valine.min.js
  disqusjs: https://cdn.jsdelivr.net/npm/disqusjs@1.2/dist/disqus.js
  disqusjs_css: https://cdn.jsdelivr.net/npm/disqusjs@1.2/dist/disqusjs.css
  utterances: https://utteranc.es/client.js

  # share
  addtoany: https://static.addtoany.com/menu/page.js
  sharejs: https://cdn.jsdelivr.net/npm/social-share.js/dist/js/social-share.min.js
  sharejs_css: https://cdn.jsdelivr.net/npm/social-share.js/dist/css/share.min.css

  # search
  local_search: /js/search/local-search.js
  algolia_js: /js/search/algolia.js
  algolia_search: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.5/dist/instantsearch.min.js
  algolia_search_css: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.5/dist/instantsearch.min.css

  # math
  mathjax: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  katex: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  katex_copytex: https://cdn.jsdelivr.net/npm/katex-copytex@latest/dist/katex-copytex.min.js
  katex_copytex_css: https://cdn.jsdelivr.net/npm/katex-copytex@latest/dist/katex-copytex.min.css
  mermaid: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

  # count
  busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

  # background effect
  canvas_ribbon: /js/third-party/canvas-ribbon.js
  canvas_ribbon_piao: /js/third-party/piao.js
  canvas_nest: /js/third-party/canvas-nest.js

  lazyload: https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js
  instantpage: https://cdn.jsdelivr.net/npm/instant.page@latest/instantpage.min.js
  typed: https://cdn.jsdelivr.net/npm/typed.js
  js_cookies: https://cdn.jsdelivr.net/npm/js-cookie/dist/js.cookie.min.js
  pangu: https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js

  # photo
  fancybox_css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.css
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
  medium_zoom: https://cdn.jsdelivr.net/npm/medium-zoom/dist/medium-zoom.min.js

  # snackbar
  snackbar_css: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css
  snackbar: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js

  # 鼠標點擊特效
  anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
  activate_power_mode: /js/third-party/activate-power-mode.js
  fireworks: /js/third-party/fireworks.js
  click_heart: /js/third-party/click_heart.js
  ClickShowText: /js/third-party/ClickShowText.js

  # fontawesome
  fontawesome_v4: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
  fontawesome_v5: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

  # 簡繁轉換
  translate: /js/tw_cn.js
